IF SCHEMA_ID(N'casino') IS NULL EXEC (N'CREATE SCHEMA casino');
IF DATABASE_PRINCIPAL_ID(N'swiftbets_app') IS NULL EXEC (N'CREATE ROLE swiftbets_app');
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::casino TO swiftbets_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::inbox TO swiftbets_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::outbox TO swiftbets_app;
